### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by DapperSFM** [ThePythonGuy3/MindBlow#3]
when I try to load the map "winter wind" it crashes the game. is there a way to fix this? (i also joined the mindustry community a month ago)

**Comment by GglLfr** [comment]
Provide a crash log hhh

**Comment by DapperSFM** [comment]
[crash-report-09_15_2020_12_58_03.txt](https://github.com/ThePythonGuy3/MindBlow/files/5284319/crash-report-09_15_2020_12_58_03.txt)
I'm not sure if this thing above will send you to see the file so ill also put the text of the crash log here:

mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveIO.load(SaveIO.java:139)
	at mindustry.io.SaveIO.load(SaveIO.java:126)
	at mindustry.maps.generators.MapGenerator.generate(MapGenerator.java:71)
	at mindustry.core.World.loadGenerator(World.java:208)
	at mindustry.core.Control.lambda$playZone$23(Control.java:256)
	at mindustry.core.UI.lambda$loadAnd$8(UI.java:235)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
Caused by: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:25)
	at mindustry.io.SaveVersion.read(SaveVersion.java:49)
	at mindustry.io.SaveIO.load(SaveIO.java:152)
	at mindustry.io.SaveIO.load(SaveIO.java:132)
	... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 200
	at mindustry.core.World$Context.tile(World.java:412)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:204)
	at mindustry.io.SaveVersion.lambda$read$0(SaveVersion.java:49)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:72)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:66)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:23)
	... 13 more

**Comment by ThePythonGuy3** [comment]
wtf what version of mindustry are you running

**Comment by DapperSFM** [comment]
idk

**Comment by DapperSFM** [comment]
i got it on itch.io

**Comment by ThePythonGuy3** [comment]
okay then it has sth to do with shop. Try to open central base pls

**Comment by DapperSFM** [comment]
how?

**Comment by ThePythonGuy3** [comment]
its a mindblow map :/

**Comment by DapperSFM** [comment]
its locked rn

**Comment by DapperSFM** [comment]
I don't know where the shop is and I don't know where the brass smelter is. im also on wave 24 of the nuke production complex

**Comment by ThePythonGuy3** [comment]
ahahhahah nuke production. Update mindblow

**Comment by DapperSFM** [comment]
oooooh

**Comment by DapperSFM** [comment]
how

**Comment by ThePythonGuy3** [comment]
delete the mod, download it again

**Comment by DapperSFM** [comment]
i did that already

**Comment by DapperSFM** [comment]
I'm also doing the import from GitHub thing

**Comment by ThePythonGuy3** [comment]
yeah that works

**Comment by ThePythonGuy3** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm very strange

**Comment by DapperSFM** [comment]
im trying it again

**Comment by DapperSFM** [comment]
ill send a crash log if there is one

**Comment by DapperSFM** [comment]
[crash-report-09_25_2020_10_38_46.txt](https://github.com/ThePythonGuy3/MindBlow/files/5284434/crash-report-09_25_2020_10_38_46.txt)

**Comment by ThePythonGuy3** [comment]
hmm i think i need to try by myself

**Comment by ThePythonGuy3** [comment]
yeah, this doesnt happen to me

**Comment by DapperSFM** [comment]
might be my laptop
its a toshiba portege

**Comment by DapperSFM** [comment]
or i need to somehow get a newer version of mindustry

**Comment by DapperSFM** [comment]
or an older one

**Comment by ThePythonGuy3** [comment]
idk how to fix this, so this is going to be closed until further notice.

**Comment by DapperSFM** [comment]
wait I just realized its version 104.10

**Comment by DapperSFM** [comment]
i think i should go to 106

**Comment by ThePythonGuy3** [comment]
nonoonoonononononn thats v6, mindblow is broken in v6

**Comment by DapperSFM** [comment]
i cant find 105

**Comment by DapperSFM** [comment]
104 seems to be the best. I'm redownloading 104
