### ISSUE TITLE
Opening Winter Wind crashes the game

### ISSUE THREAD

**Issue by deeznuts12346** [ThePythonGuy3/MindBlow#4]
mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
 at mindustry.io.SaveIO.load(SaveIO.java:139)
 at mindustry.io.SaveIO.load(SaveIO.java:126)
 at mindustry.maps.generators.MapGenerator.generate(MapGenerator.java:71)
 at mindustry.core.World.loadGenerator(World.java:208)
 at mindustry.core.Control.lambda$playZone$23(Control.java:256)
 at mindustry.core.UI.lambda$loadAnd$8(UI.java:235)
 at arc.util.Timer$1.run(Timer.java:88)
 at arc.util.TaskQueue.run(TaskQueue.java:17)
 at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
 at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
 at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
Caused by: java.io.IOException: Error reading region "map".
 at mindustry.io.SaveFileReader.region(SaveFileReader.java:25)
 at mindustry.io.SaveVersion.read(SaveVersion.java:49)
 at mindustry.io.SaveIO.load(SaveIO.java:152)
 at mindustry.io.SaveIO.load(SaveIO.java:132)
 ... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 200
 at mindustry.core.World$Context.tile(World.java:412)
 at mindustry.io.SaveVersion.readMap(SaveVersion.java:204)
 at mindustry.io.SaveVersion.lambda$read$0(SaveVersion.java:49)
 at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:72)
 at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:66)
 at mindustry.io.SaveFileReader.region(SaveFileReader.java:23)
 ... 13 more

**Comment by Comiku** [comment]
Yep; crashes when trying to open winter winds.
